/* eslint-disable */
require('./arrow-up')
require('./arrow')
require('./back-arrow')
require('./cart')
require('./close')
require('./logo-cart')
require('./profile')
require('./star')
require('./top')
require('./trash')
require('./zoom')
